### ISSUE TITLE
declaring-arrays bash tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMeBashLikeIm5#1]
Populate arrays/declaring-arrays.sh with a tutorial and challenge.

**Comment by Ordained-SubGenii** [comment]
I would like to work on this issue. I already have a tutorial more or less prepared for defining and working with indexed arrays.

**Comment by funbeedev** [comment]
@Ordained-SubGenii Sorry for the slow reply. Feel free to submit a PR if you still want to!
