### ISSUE TITLE
while-loops bash tutorial

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/TeachMeBashLikeIm5#5]
Populate loops/while-loops.sh with a tutorial and challenge.

**Comment by MalevolentStrix** [comment]
I would like to work on this issue. Can it be assigned to me @funbeedev ?

**Comment by sabderemane** [comment]
You're assigned now @MalevolentStrix !

**Comment by MalevolentStrix** [comment]
Can it be merged before the hacktoberfest gets over @sabderemane  :sweat_smile:
